CREATE DATABASE library_db
DEFAULT CHARACTER SET utf8mb4
DEFAULT COLLATE utf8mb4_general_ci;

CREATE TABLE category (
id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE author (
id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(40) NOT NULL,
nationality VARCHAR(20) NOT NULL,
birth_date DATE
);

CREATE TABLE app_user (
id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
email VARCHAR(150) NOT NULL,
phone VARCHAR(20),

is_active BOOLEAN DEFAULT TRUE,

created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE book (
id INT PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(100) NOT NULL,
isbn VARCHAR(20) NULL,
publication_year YEAR,
available BOOLEAN DEFAULT TRUE,
author_id INT NULL,
category_id INT NOT NULL,
is_active BOOLEAN DEFAULT TRUE,

FOREIGN KEY (author_id) REFERENCES author(id)
ON DELETE RESTRICT
ON UPDATE CASCADE,

FOREIGN KEY (category_id) REFERENCES category(id)
ON DELETE RESTRICT
ON UPDATE CASCADE,

created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE loan (
id INT PRIMARY KEY AUTO_INCREMENT,
app_user_id INT NOT NULL,
book_id INT NOT NULL,
loan_date DATE NOT NULL,
due_date DATE NOT NULL,
return_date DATE NULL,

FOREIGN KEY (app_user_id) REFERENCES app_user(id)
ON DELETE RESTRICT
ON UPDATE CASCADE,

FOREIGN KEY (book_id) REFERENCES book(id)
ON DELETE RESTRICT
ON UPDATE CASCADE,

created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);